before:
  hooks:
    - go mod tidy
builds:
  - binary: bridge
    env: [ CGO_ENABLED=0 ]
    goos: [ linux ]
    goarch: [ amd64 ]
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - rlcp: true
    files:
      - LICENSE
      - README.md
      - durins-bridge.service
      - durins-bridge.socket
