name: Build

on: push

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          args: build --clean --snapshot
