name: "Release: Tag"

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release binaries on GitHub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
